<footer>
    <div class="inner-container">
      <div class="fltr">
        <ul class="inline-links no-top-margin">
        <li><a href="/privacy">Privacy</a></li>
        <li><a href="/accessibility">Accessibility</a></li>
        </ul>
      </div>
        <a href="https://europa.eu/"><img src="/images/logos/eu-flag.png" height="50" alt="EU flag" class="float-left bottom-margin" loading="lazy" /></a>
        <a href="https://www.imi.europa.eu/"><img src="/images/logos/imi-logo.png" height="50" alt="IMI logo" class="float-left" loading="lazy" /></a>
        <a href="https://efpia.eu"><img src="/images/logos/efpia-logo.png" height="50" alt="EFPIA logo" class="float-left"  loading="lazy" /></a>
        <p class="low-line-height clear-left"><small>This project has received funding from the <a href="https://www.imi.europa.eu/">Innovative Medicines Initiative</a> Joint Undertaking under grant agreement No 802750. This Joint Undertaking receives support from the European Union’s Horizon 2020 research and innovation programme and EFPIA Companies. This communication reflects the views of the authors and neither IMI nor the European Union, EFPIA or any Associated Partners are liable for any use that may be made of the information contained herein.</small></p>
    </div>
    <div class="cookie-banner flex-container">
      <div class="percent-75 flexbox">
          <p>
            We use cookies to gather statistics on visits to the site, so that we can report to funders and improve the website. See our
            <a href="/privacy">privacy page</a>.
          </p>
      </div>
      <div class="flexbox">
          <button class="button rounded cookie-btn cookie-accept red-background top-margin dark-bg">
            Accept cookies
          </button>
      </div>
      <div class="flexbox">
          <button class="button rounded cookie-btn cookie-reject grey-background top-margin dark-bg">
            Reject
          </button>
      </div>
    </div>
</footer>

</body>
</html>
