<footer>
    <div class="inner-container">
        <a href="https://europa.eu/"><img src="/images/logos/eu-flag.png" height="50" alt="EU flag" class="float-left bottom-margin"/></a>
        <a href="https://www.imi.europa.eu/"><img src="/images/logos/imi-logo.png" height="50" alt="IMI logo" class="float-left" /></a>
        <a href="https://efpia.eu"><img src="/images/logos/efpia-logo.png" height="50" alt="EFPIA logo" class="float-left" /></a>
        <p class="low-line-height clear-left"><small>This project has received funding from the <a href="https://www.imi.europa.eu/">Innovative Medicines Initiative</a> 2 Joint Undertaking under grant agreement No 802750. This Joint Undertaking receives support from the European Union’s Horizon 2020 research and innovation programme and EFPIA Companies. This communication reflects the views of the authors and neither IMI nor the European Union, EFPIA or any Associated Partners are liable for any use that may be made of the information contained herein.</small></p>
    </div>
</footer>
</body>
</html>
