<div class="tinted inner-padding small-text">
  <h2 class="no-top-margin line-height-1">Stay in touch</h2>
  <div class="top-margin text-white">
    <a href="https://twitter.com/intent/follow?original_referer=https%3A%2F%2Ffairplus-project.eu%2Fget-involved%2F&ref_src=twsrc%5Etfw&region=follow_link&screen_name=FAIRplus_eu&tw_p=followbutton" class="button subscribe twitter">Follow us on Twitter</a>
  </div>
  <div class="top-margin text-white">
    <a href="http://eepurl.com/ghuHeT" class="button subscribe newsletter">Subscribe to our newsletter</a>
  </div>
</div>
