<nav class="subnav xx-bottom-margin">
   <h2><a href="/choosing-data/" <?php echo ($page == 'choosing-data')? 'class="active"' : ''; ?>>Datasets</a></h2>
   <ul>
     <li><a href="datasets-2020"<?php echo ($page == 'datasets-2020')? ' class="active"' : ''; ?>>Datasets 2020</a></li>
      <li><a href="datasets-2019"<?php echo ($page == 'datasets-2019')? ' class="active"' : ''; ?>>Datasets 2019</a></li>
   </ul>
</nav>