              <nav class="subnav">
                 <h2><a href="/resources/" <?php echo ($page == 'resources')? 'class="active"' : ''; ?>>Resources</a></h2>
                 <ul>
                   <li><a href="suggested-reading"<?php echo ($page == 'suggested-reading')? ' class="active"' : ''; ?>>Suggested reading</a></li>
                    <li><a href="publicity-materials"<?php echo ($page == 'publicity-materials')? ' class="active"' : ''; ?>>Publicity materials</a></li>
                    <!-- <li><a href="approach-fairification" --><?php echo ($page == 'approach-fairification')? ' class="active"' : ''; ?><!-- >The approach to FAIRification</a></li> -->
                    <li><a href="logos"<?php echo ($page == 'logos')? ' class="active"' : ''; ?>>FAIRplus logos</a></li>
                 </ul>
              </nav>
