<nav class="subnav">
                 <h2><a href="/about/" <?php echo ($page == 'about')? 'class="active"' : ''; ?>>About the project</a></h2>
                 <ul>
                    <li><a href="/about/how-project-organised"<?php echo ($page == 'how-project-organised')? ' class="active"' : ''; ?>>How the project is organised</a></li>
                    <!-- <li><a href="approach-fairification" --><?php echo ($page == 'approach-fairification')? ' class="active"' : ''; ?><!-- >The approach to FAIRification</a></li> -->
                    <li><a href="/about/deliverables"<?php echo ($page == 'deliverables')? ' class="active"' : ''; ?>>Deliverables and milestones</a></li>
                    <li><a href="/about/governance"<?php echo ($page == 'governance')? ' class="active"' : ''; ?>>Governance</a></li>
                    <!--<li><a href="/about/news/"<?php /*echo ($page == 'news')? ' class="active"' : ''; */?>>News</a></li>-->
                 </ul>
              </nav>