<nav class="subnav">
                 <h2><a href="/get-involved/" <?php echo ($page == 'get-involved')? 'class="active"' : ''; ?>>Get involved</a></h2>
                 <ul>
                   <li><a href="/get-involved/innovation-sme-forum"<?php echo ($page == 'SME Forum')? ' class="active"' : ''; ?>>Innovation and SME Forums</a></li>
                   <li><a href="/get-involved/fellowship-apply"<?php echo ($page == 'fellowship')? ' class="active"' : ''; ?>>Fellowship Programme</a></li>
                 </ul>
              </nav>